export const PHASE2A_PERMISSION_KEYS = [
  'schedule.viewOwn',
  'schedule.view',
  'schedule.create',
  'schedule.update',
  'schedule.cancel',
  'attendance.clock',
  'attendance.viewOwn',
  'attendance.view',
  'attendance.correct.request',
  'attendance.correct.approve',
  'workSession.start',
  'workSession.end',
  'workSession.startUnscheduled',
  'workSession.forceEnd',
  'workSession.view',
  'leave.viewOwn',
  'leave.request',
  'leave.view',
  'leave.approve',
  'leave.reject',
  'leave.return',
  'leave.attachment.upload',
  'leave.attachment.view',
  'leave.balance.viewOwn',
  'leave.balance.view',
  'leave.policy.view',
  'leave.policy.manage',
  'leave.interview.record',
] as const;

export const PHASE2A1_PERMISSION_KEYS = [
  'staffingRequirement.view',
  'staffingRequirement.manage',
] as const;

export const PHASE2B1_PERMISSION_KEYS = [
  'qrAsset.view',
  'qrAsset.create',
  'qrAsset.deactivate',
  'qrAsset.reactivate',
  'qrAsset.export',
  'qrScan.use',
  'qrScan.viewHistory',
  'employeeQr.viewOwn',
] as const;

export const PHASE2B2_PERMISSION_KEYS = [
  'patrolPoint.view',
  'patrolPoint.manage',
  'patrolTemplate.view',
  'patrolTemplate.manage',
  'patrol.viewOwn',
  'patrol.view',
  'patrol.execute',
  'patrol.manualOverride',
  'patrolException.create',
  'patrolException.view',
  'patrolException.manage',
  'patrolDashboard.view',
] as const;

export const PHASE2C_PERMISSION_KEYS = [
  'inspection.scan',
  'inspection.create',
  'inspection.viewOwn',
  'inspection.view',
  'inspection.evaluate',
  'inspection.evidence.upload',
  'inspectionCriteria.view',
  'inspectionCriteria.manage',
  'improvement.create',
  'improvement.view',
  'improvement.review',
  'improvement.close',
  'discipline.recommend',
  'discipline.review',
  'discipline.approve',
  'inspectionDashboard.view',
] as const;
